services:
    # Gallery
    dog_main_gallery_admin:
        class: Dog\MainBundle\Admin\GalleryAdmin
        arguments: [ @dog_main.gallery_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }
        calls:
            - [addChild, [@dog_main_gallery_image_admin]]

    dog_main.gallery_manager:
        class: %msi_admin.manager.class%
        arguments: [ Dog\MainBundle\Entity\Gallery ]
        parent: msi_admin.manager

    # GalleryImage
    dog_main_gallery_image_admin:
        class: Dog\MainBundle\Admin\GalleryImageAdmin
        arguments: [ @dog_main.gallery_image_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }
        calls:
            - [ setParent, [ @dog_main_gallery_admin ] ]

    dog_main.gallery_image_manager:
        class: %msi_admin.manager.class%
        arguments: [ Dog\MainBundle\Entity\GalleryImage ]
        parent: msi_admin.manager

    # Package
    dog_main_package_admin:
        class: Dog\MainBundle\Admin\PackageAdmin
        arguments: [ @dog_main.package_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    dog_main.package_manager:
        class: %msi_admin.manager.class%
        arguments: [ Dog\MainBundle\Entity\Package ]
        parent: msi_admin.manager

    # Service
    dog_main_service_admin:
        class: Dog\MainBundle\Admin\ServiceAdmin
        arguments: [ @dog_main.service_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    dog_main.service_manager:
        class: %msi_admin.manager.class%
        arguments: [ Dog\MainBundle\Entity\Service ]
        parent: msi_admin.manager

    # Testimonial
    dog_main_testimonial_admin:
        class: Dog\MainBundle\Admin\TestimonialAdmin
        arguments: [ @dog_main.testimonial_manager ]
        parent: msi_admin.admin
        tags:
            - { name: msi.admin }

    dog_main.testimonial_manager:
        class: %msi_admin.manager.class%
        arguments: [ Dog\MainBundle\Entity\Testimonial ]
        parent: msi_admin.manager
