parameters:
#    dog_user.example.class: Dog\UserBundle\Example

services:
#    dog_user.example:
#        class: %dog_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
